### PR TITLE
#5/ease the creation of scenarios s1 s2 and s3

### PR DESCRIPTION
**Pull request by tomschw**
Notebooks now automatically create all three strategies outlined in the paper. All three strategies are applied each for the same situation(same customer and same competitors), which should improve comparability.

### CODE REVIEW

**Comment by tomschw** [comment]
ping @Bouncner

**Comment by Bouncner** [comment]
First thing: could you please add a short description of the three scenarios to the market_place notebook?

**Comment by Bouncner** [comment]
Didn't know branch names can include hashes. That's scary.  😲

Update: aaaand it is scary ...
```
➜  pricing_competition_simulation git:(master) ✗ git checkout origin/#5/ease_the_creation_of_scenarios_S1_S2_and_S3
zsh: bad pattern: origin/#5/ease_the_creation_of_scenarios_S1_S2_and_S3

➜  pricing_competition_simulation git:(master) ✗ git checkout origin/\#5/ease_the_creation_of_scenarios_S1_S2_and_S3
(eval):1: bad pattern: origin/#5/ease_the_creation_of_scenarios_S1_S2_and_S3

➜  pricing_competition_simulation git:(master) ✗ git checkout '#5/ease_the_creation_of_scenarios_S1_S2_and_S3'
Your branch is up-to-date with 'origin/master'.
```

Update: choosing bash over zsh helped to checkout the branch. 🤦

**Comment by tomschw** [comment]
It's curious that escaping the hash doesn't work. Maybe using single quotes around the path would help in zsh?

As every branch should be a feature branch with an issue it's easier to keep track of them with the issue number and name as branch name. Is it bad style or something?

**Comment by tomschw** [comment]
Added small descriptions for each startegy. Any changes necessary?(more detail, description not really understandable)

**Comment by Bouncner** [comment]
Can you please add more information about S2? I don't get what you're doing there. :)

PS: using quotes does not help with zsh shell.

**Comment by tomschw** [comment]
Is the description clearer ?

**Comment by Bouncner** [comment]
I think is better, but not sufficiently clear yet. Do you think we should use pseudo code?

**Comment by tomschw** [comment]
It would probably be easier. Maybe:
The pricing strategy is the same for each company. The price is set according to the following pseudo code:
If min(prices_companies) < 5 then 10 else max(4.9, (min(prices_companies)-0.5))

**Comment by Bouncner** [comment]
Sounds much better to me. Maybe like this in pseudo Python code:
```
min_competitor_price = min(prices_companies)
if min_competitor_price < 5:
    10
else:
    max(4.9, (min_competitor_price - 0.5))
```

We use Python anyway and I think we can't write it simple enough. What do you think?

**Comment by tomschw** [comment]
Looks good, added it in last commit.

**Pull request merged**
