### PR TITLE
Plot price trajectories

### LINKED ISSUE #6: Plot price trajectories
Currently, we create a trajectory output CSV with which we plot the trajectory graphs.

To improve the user's understanding of the notebooks, let's skip the CSV and plot directly.

### PR DESCRIPTION
**Pull request by tomschw**
Resolve #6

### CODE REVIEW

**Comment by tomschw** [comment]
I would like feedback on the graph. Is it comprehensible? Would you like a different time period?

**Comment by Bouncner** [comment]
Rainer and me currently cannot run notebooks. Could you add a screenshot please?

**Comment by tomschw** [comment]
You can simply look at the final notebook with graphs here:
https://github.com/hpi-epic/pricing_competition_simulation/blob/23652ebb67f1f32e949fa3136215ef8330bfda0c/market_simulation.ipynb
I've also fixed some huge bugs resulting in the fact that prices nearly never changed and that the times when companies adjusted their prices where nearly always random with no structure, like expected.

**Comment by Bouncner** [comment]
Rainers Fax cannot display wesites and I am on a mobile (shows only the JSON). ;)

But ok. I’ll take a lot later.

**Comment by tomschw** [comment]
graphs

**Comment by tomschw** [comment]
Changed the things Rainer wanted changed. Maybe let him take a look at the graphs, if everything is looking fine for him. @Bouncner

**Comment by Bouncner** [comment]
Please change legend in intensitivity notebook from S1 to “Setup 1”.

**Comment by tomschw** [comment]
Done.

**Pull request merged**
