### PR TITLE
Create plot for conditional probabilities 

### LINKED ISSUE #7: Plots für Conditional Probabilities
Similar to #6 , let's plot the conditional probabilities directly within the notebookl

### PR DESCRIPTION
**Pull request by tomschw**
Resolve #7

### CODE REVIEW

**Comment by Bouncner** [comment]
Looks good to me, but is there something we can do about the issue that the graphs look so random for the generated data?

Do you think there's a sweet spot of data to generate where it's still "fast enough" for users but also large enough to draw nicer graphs?

**Comment by tomschw** [comment]
I split up monte_carlo and intensity, now it the graph looks better and it's way faster.

**Comment by Bouncner** [comment]
I am not happy with having the s1-s3 dictionaries of functions declared in several notebooks. But using `%store` does not work as the lambdas cannot be pickled.

We need to find a way to better deal with that.

**Comment by tomschw** [comment]
It seems like Dill works in 3.6 with all object types from Python. Maybe we should try that.

**Comment by Bouncner** [comment]
Dill locks quite nice. But since I just tested the dict for S3: are you sure that ['3']() creates a new random price every time called?

**Comment by tomschw** [comment]
I should rewrite that and remove the random. It is really supposed to just return 11, so if it does that all the time everything works fine.

**Comment by Bouncner** [comment]
Ok. Can you create a PR for the fix or an issue if you don't have the time to fix it right now?

**Pull request merged**
